"use client";
import { useState } from "react";
import Link from "next/link";
import { Loader2, Send, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import type { AdvisorAnswer } from "@/lib/advisor/types";

const SUGGESTIONS = [
  "Which AI initiatives generated the highest validated benefit?",
  "Where are we losing AI value?",
  "Which processes have low adoption?",
  "Why is the Procurement Sourcing Agent below its ROI target?",
  "What happens if AI costs increase by 30%?",
  "Which processes have released the most capacity?",
  "Show Finance initiatives with payback under 12 months.",
];

export function AdvisorPanel() {
  const [q, setQ] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [history, setHistory] = useState<AdvisorAnswer[]>([]);

  async function ask(question: string) {
    if (question.trim().length < 3) return;
    setLoading(true);
    setError(null);
    try {
      const r = await fetch("/api/advisor", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question }) });
      const data = await r.json();
      if (!r.ok) throw new Error(data.error ?? "Request failed");
      setHistory((h) => [data as AdvisorAnswer, ...h]);
      setQ("");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-1.5">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          <span className="hidden sm:inline">AI Value Advisor</span>
        </Button>
      </DialogTrigger>
      <DialogContent side="right" className="max-w-lg">
        <DialogHeader>
          <DialogTitle>AI Value Advisor</DialogTitle>
          <DialogDescription>
            Answers come from deterministic queries over the platform&apos;s structured data. No financial figures are generated by a language model.
          </DialogDescription>
        </DialogHeader>
        <form
          className="flex gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            void ask(q);
          }}
        >
          <Input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Ask about value, adoption, leakage, payback…" aria-label="Question" />
          <Button type="submit" size="icon" className="h-9 w-9 shrink-0" disabled={loading} aria-label="Ask">
            {loading ? <Loader2 className="animate-spin" /> : <Send />}
          </Button>
        </form>
        {error && <p className="text-xs text-red-700">{error}</p>}
        {history.length === 0 && (
          <div className="flex flex-col gap-1.5">
            <p className="eyebrow">Try asking</p>
            {SUGGESTIONS.map((s) => (
              <button key={s} onClick={() => void ask(s)} className="rounded-md border px-3 py-2 text-left text-xs hover:bg-muted">
                {s}
              </button>
            ))}
          </div>
        )}
        <div className="flex flex-col gap-4">
          {history.map((a, i) => (
            <div key={i} className="space-y-2 rounded-lg border p-3">
              <p className="text-xs font-medium text-primary">{a.question}</p>
              <p className="text-sm leading-relaxed">{a.text}</p>
              {a.bullets && (
                <ul className="list-disc space-y-1 pl-4 text-xs text-muted-foreground">
                  {a.bullets.map((b, k) => (
                    <li key={k}>{b}</li>
                  ))}
                </ul>
              )}
              {a.table && a.table.rows.length > 0 && (
                <div className="overflow-x-auto rounded border">
                  <table className="w-full text-[11px] tabular">
                    <thead className="bg-muted/50">
                      <tr>
                        {a.table.columns.map((c) => (
                          <th key={c} className="px-2 py-1 text-left font-medium text-muted-foreground">
                            {c}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {a.table.rows.map((r, k) => (
                        <tr key={k} className="border-t">
                          {r.map((c, j) => (
                            <td key={j} className="px-2 py-1">
                              {c}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
              {a.links && (
                <div className="flex flex-wrap gap-2">
                  {a.links.map((l) => (
                    <Link key={l.href} href={l.href} className="text-xs text-primary underline-offset-2 hover:underline">
                      {l.label} →
                    </Link>
                  ))}
                </div>
              )}
              <p className="text-[10px] text-muted-foreground">Intent: {a.intent} · narrated by: {a.narratedBy}</p>
            </div>
          ))}
        </div>
      </DialogContent>
    </Dialog>
  );
}
